In [1]:
import torch

tensor_a = torch.tensor([[1, 2], 
                        [3, 4]])

tensor_b = torch.tensor([[5, 6], 
                        [7, 8]])

transposed_tensor = torch.transpose(tensor_a, 0, 1)
print("1. Transposition:")
print(transposed_tensor)

sqrt_tensor = torch.sqrt(tensor_a.float())
print("\n2. Element-wise square root:")
print(sqrt_tensor)

concatenated_tensor = torch.cat((tensor_a, tensor_b), dim=1)
print("\n3. Concatenation along dimension 1:")
print(concatenated_tensor)

abs_tensor = torch.abs(tensor_a - tensor_b)
print("\n4. Element-wise absolute value:")
print(abs_tensor)

sum_along_dimension = torch.sum(tensor_a, dim=1)
print("\n5. Reduction operation - Sum along dimension 1:\n")
print(sum_along_dimension)

a=torch.tensor([1, 4, 6, 8, 10, 14])
cla=torch.clamp(a,min=5,max=10)
print("\n6. Clamp: ",cla)

b=torch.linspace(start=1,end=10,steps=5)
print("\n7. Creating an Equally spaced tensor : \n",b)

c=torch.eye(n=4,m=5)
print("\n8. Creating a tensor with 1's in leading Diagonal : \n",c)

d=torch.full(size=[2,3,4],fill_value=5)
print("\n9. Creating a tensor with a fill value:\n",d)

e=torch.tensor([[1, 2, 6], [3, 4, 7]])
print("\n10. Taking the element at specified index : \n")
torch.take(e,torch.tensor([2,5]))

f=torch.tensor([[1,2,3],
                [4,5,6]])
print("\n11. Removes a tensor dimension : \n")
torch.unbind(f,dim=1)

g=torch.tensor([[1,2],
                [3,4],
                [5,6]])
h=g.clone()
print("\n12. Creating a deepcopy of a tensor : \n")
print(h)

1. Transposition:
tensor([[1, 3],
        [2, 4]])

2. Element-wise square root:
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])

3. Concatenation along dimension 1:
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

4. Element-wise absolute value:
tensor([[4, 4],
        [4, 4]])

5. Reduction operation - Sum along dimension 1:

tensor([3, 7])

6. Clamp:  tensor([ 5,  5,  6,  8, 10, 10])

7. Creating an Equally spaced tensor : 
 tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

8. Creating a tensor with 1's in leading Diagonal : 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

9. Creating a tensor with a fill value:
 tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])

10. Taking the element at specified index : 


11. Removes a tensor dimension : 


12. Creating a deepcopy of a tensor : 

tensor([[1, 2],
        [3, 